# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

dist: trusty
sudo: false
language: node_js

addons:
  firefox: latest
  chrome: stable

matrix:
  include:
    # Local Browsers
    - node_js: 8
      env: KARMA=true KARMA_COVERAGE=true

    # Sauce Labs
    - node_js: 8
      env: KARMA=true KARMA_SAUCE=true

    # Node
    - node_js: 4
    - node_js: 5
    - node_js: 6
    - node_js: 7

before_script:
  # Setup a virtual display for browser testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  # concatenate all code-coverage data into a single file
  - ls -R1 coverage/*/lcov.info
  - cat coverage/*/lcov.info > ./coverage/lcov.info

  # send code-coverage data to Codacy
  - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage -p .

  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
