# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

filter_secrets: false
language: node_js

node_js:
  - 8
  - 10
  - 12

os:
  - linux
  - osx
  - windows

before_script:
  - npm run lint

script:
  - npm run coverage:node

after_success:
  # concatenate all code-coverage data into a single file
  - ls -Rlh coverage/*/lcov.info
  - cat coverage/*/lcov.info > ./coverage/lcov.info

  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - name: Browser tests (Linux)
      os: linux
      script: npm run coverage:browser
      addons:
        firefox: latest
        chrome: stable

    - name: Browser tests (Mac)
      os: osx
      script: npm run coverage:browser
      addons:
        firefox: latest
        chrome: stable

    - name: Browser tests (Windows via SauceLabs)
      os: linux
      script: npm run coverage:browser
      env: WINDOWS=true

    - stage: Deploy
      name: Publish to npm
      script: npm run build
      after_success: true
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
          branch: master
