remote_theme: APIDevTools/gh-pages-theme

title: Swagger Parser
logo: https://apidevtools.org/img/logos/logo.png

author:
  twitter: APIDevTools

google_analytics: UA-68102273-2

twitter:
  username: APIDevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://apidevtools.org/img/logos/card.png

  - scope:
      path: "test/specs/**/*"
    values:
      sitemap: false

  - scope:
      path: "www/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
